[tool.poetry]
name = "synthetic-data"
version = "0.1.0"
description = ""
authors = ["Andres Gonzalez <andres@aihealth.sg>"]
readme = "README.md"
packages = [{include = "synthetic_data"}]

[tool.poetry.dependencies]
python = "^3.10"
Faker = "^29.0.0"
marshmallow = "^3.22.0"
tqdm = "^4.66.5"
snakeviz = "^2.2.0"
pyinstrument = "^4.7.3"
jupyterlab = "^4.2.5"
jupyter-summarytools = "^0.2.3"
sweetviz = "^2.3.1"
pandas = "^2.2.3"
numpy = "1.26.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
